[[constraint]]
  name = "github.com/Sirupsen/logrus"
  version = "1.2.0"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "0.9.2"

[prune]
  go-tests = true
  unused-packages = true
