kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: dummy-exporter
  namespace: default
spec:
  replicas: 3
  template:
    metadata:
      namespace: default
      labels:
        app: dummy-exporter
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9100"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: dummy-exporter
        image: bigfattoby/prom-dummy-exporter
        imagePullPolicy: Always
      nodeSelector:
        beta.kubernetes.io/os: linux
